### ISSUE TITLE
Option for import_agr to use only the skeletons

### ISSUE THREAD

**Issue by Darkhandrob** [advancedfx/afx-blender-scripts#2]
Since most UE4 Users import their models and animations seperate, it would be useful to add an option for the agr importer to use the models in csgo/player/custom_player/scaffold_t and /scaffold_ct. These models are without the meshes and only have the skeletons, which makes them much faster to import and export. 
Importing them once and copying them should improve the runtime even more.

**Comment by dtugend** [comment]
Thanks for your suggestion.

I did it a bit differently, it imports the skeletons of the original models only, since they might differ sometimes.

Please try [afx-blender-scripts v1.6.0 (2018-10-05T17:45Z)](https://github.com/advancedfx/afx-blender-scripts/releases/latest) or newer:

Added option "Bones (skeleton) only".
